use crate::backend::CodegenBackend;
use crate::ir::{Module, Function, Instruction, Type};
use std::error::Error;

/// 8cc 后端代码生成器
/// 
/// 8cc 是 Rui Ueyama 开发的教育型 C 编译器
/// 特性：
/// - 简洁的 C89/C99 子集
/// - 适合教学和学习
/// - 轻量级实现
pub struct Cc8Backend {
    /// 使用严格的 C89 标准
    pub strict_c89: bool,
}

impl Cc8Backend {
    pub fn new() -> Self {
        Self {
            strict_c89: false,
        }
    }

    fn generate_type(&self, ty: &Type) -> String {
        match ty {
            Type::Void => "void".to_string(),
            Type::Int32 => "int".to_string(),
            Type::Int64 => "long long".to_string(),
            Type::Float32 => "float".to_string(),
            Type::Float64 => "double".to_string(),
            Type::Bool => "int".to_string(),  // C89 没有 bool
            Type::String => "char*".to_string(),
            Type::Ptr(inner) | Type::Ref(inner) | Type::MutRef(inner) => {
                format!("{}*", self.generate_type(inner))
            },
            Type::Array(inner, size) => {
                format!("{}[{}]", self.generate_type(inner), size)
            },
            Type::Struct(name) => format!("struct {}", name),
        }
    }

    fn generate_function(&self, func: &Function) -> String {
        let mut code = String::new();
        
        let return_type = self.generate_type(&func.return_type);
        let params = func.params
            .iter()
            .map(|(name, ty)| format!("{} {}", self.generate_type(ty), name))
            .collect::<Vec<_>>()
            .join(", ");
        
        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params
        };
        
        code.push_str(&format!("{} {}({}) {{\n", return_type, func.name, params_str));
        
        for inst in &func.body {
            code.push_str(&self.generate_instruction(inst));
        }
        
        code.push_str("}\n");
        code
    }

    fn generate_instruction(&self, inst: &Instruction) -> String {
        match inst {
            Instruction::Alloca { dest, ty } => {
                format!("    {} {};\n", self.generate_type(ty), dest)
            },
            Instruction::Store { dest, src } => {
                format!("    {} = {};\n", dest, src)
            },
            Instruction::Load { dest, src } => {
                format!("    int {} = {};\n", dest, src)
            },
            Instruction::Add { dest, left, right } => {
                format!("    int {} = {} + {};\n", dest, left, right)
            },
            Instruction::Sub { dest, left, right } => {
                format!("    int {} = {} - {};\n", dest, left, right)
            },
            Instruction::Mul { dest, left, right } => {
                format!("    int {} = {} * {};\n", dest, left, right)
            },
            Instruction::Div { dest, left, right } => {
                format!("    int {} = {} / {};\n", dest, left, right)
            },
            Instruction::Mod { dest, left, right } => {
                format!("    int {} = {} % {};\n", dest, left, right)
            },
            Instruction::Call { dest, func, args } => {
                if let Some(dest) = dest {
                    format!("    int {} = {}({});\n", dest, func, args.join(", "))
                } else {
                    format!("    {}({});\n", func, args.join(", "))
                }
            },
            Instruction::Return(value) => {
                if let Some(val) = value {
                    format!("    return {};\n", val)
                } else {
                    "    return;\n".to_string()
                }
            },
            Instruction::ReturnInPlace(value) => {
                format!("    return {}; /* RVO */\n", value)
            },
            _ => format!("    /* {:?} */\n", inst),
        }
    }
}

impl CodegenBackend for Cc8Backend {
    fn name(&self) -> &str {
        "8cc"
    }

    fn generate(&self, module: &Module) -> Result<String, Box<dyn Error>> {
        let mut code = String::new();
        
        code.push_str("/* Generated by Chim Compiler - 8cc Backend */\n");
        code.push_str("/* Target: 8cc (Rui Ueyama's Educational C Compiler) */\n");
        code.push_str("/* C89/C99 subset */\n\n");
        
        code.push_str("#include <stdio.h>\n");
        code.push_str("#include <stdlib.h>\n\n");
        
        for func in &module.functions {
            code.push_str(&self.generate_function(func));
            code.push_str("\n");
        }
        
        Ok(code)
    }

    fn file_extension(&self) -> &str {
        "c"
    }
}
