use crate::backend::CodegenBackend;
use crate::ir::{Module, Function, Instruction, Type};
use std::error::Error;

/// GCC 后端代码生成器
/// 
/// GNU Compiler Collection
/// 特性：
/// - GNU C 扩展支持
/// - 内联汇编
/// - 优化属性
/// - 向量扩展
pub struct GCCBackend {
    pub use_gnu_extensions: bool,
    pub optimization_hints: bool,
}

impl GCCBackend {
    pub fn new() -> Self {
        Self {
            use_gnu_extensions: true,
            optimization_hints: true,
        }
    }

    fn generate_type(&self, ty: &Type) -> String {
        match ty {
            Type::Void => "void".to_string(),
            Type::Int32 => "int32_t".to_string(),
            Type::Int64 => "int64_t".to_string(),
            Type::Float32 => "float".to_string(),
            Type::Float64 => "double".to_string(),
            Type::Bool => "_Bool".to_string(),
            Type::String => "char*".to_string(),
            Type::Ptr(inner) | Type::Ref(inner) | Type::MutRef(inner) => {
                format!("{}*", self.generate_type(inner))
            },
            Type::Array(inner, size) => {
                format!("{}[{}]", self.generate_type(inner), size)
            },
            Type::Struct(name) => format!("struct {}", name),
        }
    }

    fn generate_function(&self, func: &Function) -> String {
        let mut code = String::new();
        
        if self.optimization_hints {
            code.push_str("__attribute__((hot))\n");
        }
        
        let return_type = self.generate_type(&func.return_type);
        let params = func.params
            .iter()
            .map(|(name, ty)| format!("{} {}", self.generate_type(ty), name))
            .collect::<Vec<_>>()
            .join(", ");
        
        code.push_str(&format!("{} {}({}) {{\n", return_type, func.name, params));
        
        for inst in &func.body {
            code.push_str(&self.generate_instruction(inst));
        }
        
        code.push_str("}\n");
        code
    }

    fn generate_instruction(&self, inst: &Instruction) -> String {
        match inst {
            Instruction::Alloca { dest, ty } => {
                format!("    {} {};\n", self.generate_type(ty), dest)
            },
            Instruction::Store { dest, src } => {
                format!("    {} = {};\n", dest, src)
            },
            Instruction::Load { dest, src } => {
                format!("    __auto_type {} = {};\n", dest, src)
            },
            Instruction::Add { dest, left, right } => {
                format!("    __auto_type {} = {} + {};\n", dest, left, right)
            },
            Instruction::Sub { dest, left, right } => {
                format!("    __auto_type {} = {} - {};\n", dest, left, right)
            },
            Instruction::Mul { dest, left, right } => {
                format!("    __auto_type {} = {} * {};\n", dest, left, right)
            },
            Instruction::Div { dest, left, right } => {
                format!("    __auto_type {} = {} / {};\n", dest, left, right)
            },
            Instruction::Mod { dest, left, right } => {
                format!("    __auto_type {} = {} % {};\n", dest, left, right)
            },
            Instruction::Call { dest, func, args } => {
                if let Some(dest) = dest {
                    format!("    __auto_type {} = {}({});\n", dest, func, args.join(", "))
                } else {
                    format!("    {}({});\n", func, args.join(", "))
                }
            },
            Instruction::Return(value) => {
                if let Some(val) = value {
                    format!("    return {};\n", val)
                } else {
                    "    return;\n".to_string()
                }
            },
            Instruction::ReturnInPlace(value) => {
                format!("    return {}; /* RVO */\n", value)
            },
            _ => format!("    /* {:?} */\n", inst),
        }
    }
}

impl CodegenBackend for GCCBackend {
    fn name(&self) -> &str {
        "GCC"
    }

    fn generate(&self, module: &Module) -> Result<String, Box<dyn Error>> {
        let mut code = String::new();
        
        code.push_str("/* Generated by Chim Compiler - GCC Backend */\n");
        code.push_str("/* Target: GNU Compiler Collection */\n");
        code.push_str("/* GNU C Extensions enabled */\n\n");
        
        code.push_str("#include <stdio.h>\n");
        code.push_str("#include <stdint.h>\n");
        code.push_str("#include <stdbool.h>\n\n");
        
        for func in &module.functions {
            code.push_str(&self.generate_function(func));
            code.push_str("\n");
        }
        
        Ok(code)
    }

    fn file_extension(&self) -> &str {
        "c"
    }
}
