use crate::backend::CodegenBackend;
use crate::ir::{Module, Function, Instruction, Type};
use std::error::Error;

pub struct MatlabBackend;

impl MatlabBackend {
    pub fn new() -> Self {
        Self
    }
    
    fn generate_type(&self, ty: &Type) -> String {
        match ty {
            Type::Void => "".to_string(),
            Type::Int32 | Type::Int64 => "int64".to_string(),
            Type::Float32 | Type::Float64 => "double".to_string(),
            Type::Bool => "logical".to_string(),
            Type::String => "string".to_string(),
            Type::Ptr(_) => "handle".to_string(),
            _ => "any".to_string(),
        }
    }
    
    fn generate_function(&self, func: &Function) -> String {
        let mut output = String::new();
        
        // 函数签名
        output.push_str("function ");
        
        if func.return_type != Type::Void {
            output.push_str("result = ");
        }
        
        output.push_str(&format!("{}(", func.name));
        
        // 参数
        let param_names: Vec<String> = func.params.iter()
            .map(|(name, _)| name.clone())
            .collect();
        output.push_str(&param_names.join(", "));
        
        output.push_str(")\n");
        
        // 函数体
        for inst in &func.body {
            output.push_str(&self.generate_instruction(inst));
        }
        
        output.push_str("end\n");
        output
    }
    
    fn generate_instruction(&self, inst: &Instruction) -> String {
        match inst {
            Instruction::Alloca { dest, .. } => {
                format!("    {} = [];\n", dest)
            },
            Instruction::Add { dest, left, right } => {
                format!("    {} = {} + {};\n", dest, left, right)
            },
            Instruction::Sub { dest, left, right } => {
                format!("    {} = {} - {};\n", dest, left, right)
            },
            Instruction::Mul { dest, left, right } => {
                format!("    {} = {} * {};\n", dest, left, right)
            },
            Instruction::Div { dest, left, right } => {
                format!("    {} = {} / {};\n", dest, left, right)
            },
            Instruction::Mod { dest, left, right } => {
                format!("    {} = mod({}, {});\n", dest, left, right)
            },
            Instruction::Eq { dest, left, right } => {
                format!("    {} = ({} == {});\n", dest, left, right)
            },
            Instruction::Ne { dest, left, right } => {
                format!("    {} = ({} ~= {});\n", dest, left, right)
            },
            Instruction::Lt { dest, left, right } => {
                format!("    {} = ({} < {});\n", dest, left, right)
            },
            Instruction::Le { dest, left, right } => {
                format!("    {} = ({} <= {});\n", dest, left, right)
            },
            Instruction::Gt { dest, left, right } => {
                format!("    {} = ({} > {});\n", dest, left, right)
            },
            Instruction::Ge { dest, left, right } => {
                format!("    {} = ({} >= {});\n", dest, left, right)
            },
            Instruction::And { dest, left, right } => {
                format!("    {} = ({} && {});\n", dest, left, right)
            },
            Instruction::Or { dest, left, right } => {
                format!("    {} = ({} || {});\n", dest, left, right)
            },
            Instruction::Not { dest, src } => {
                format!("    {} = ~{};\n", dest, src)
            },
            Instruction::Store { dest, src } => {
                format!("    {} = {};\n", dest, src)
            },
            Instruction::Load { dest, src } => {
                format!("    {} = {};\n", dest, src)
            },
            Instruction::Return(Some(value)) => {
                format!("    result = {};\n", value)
            },
            Instruction::Return(None) => {
                "".to_string()
            },
            Instruction::ReturnInPlace(value) => {
                format!("    result = {}; % RVO优化\n", value)
            },
            Instruction::Call { dest, func, args } => {
                let args_str = args.join(", ");
                if let Some(d) = dest {
                    format!("    {} = {}({});\n", d, func, args_str)
                } else {
                    format!("    {}({});\n", func, args_str)
                }
            },
            _ => format!("    %% Unsupported: {:?}\n", inst),
        }
    }
}

impl CodegenBackend for MatlabBackend {
    fn name(&self) -> &str {
        "MATLAB"
    }
    
    fn generate(&self, module: &Module) -> Result<String, Box<dyn Error>> {
        let mut output = String::new();
        
        // 文件头注释
        output.push_str("% Generated by Chim Compiler\n");
        output.push_str("% MATLAB Backend\n\n");
        
        // 生成所有函数
        for func in &module.functions {
            output.push_str(&self.generate_function(func));
            output.push('\n');
        }
        
        Ok(output)
    }
    
    fn file_extension(&self) -> &str {
        "m"
    }
}
