use crate::backend::CodegenBackend;
use crate::ir::{Module, Function, Instruction, Type};
use std::error::Error;

/// Rustc 后端代码生成器
/// 
/// Rust 编译器后端，生成 Rust 代码
/// 特性：
/// - 内存安全
/// - 零成本抽象
/// - 所有权系统
pub struct RustcBackend {
    pub use_unsafe: bool,
}

impl RustcBackend {
    pub fn new() -> Self {
        Self {
            use_unsafe: false,
        }
    }

    fn generate_type(&self, ty: &Type) -> String {
        match ty {
            Type::Void => "()".to_string(),
            Type::Int32 => "i32".to_string(),
            Type::Int64 => "i64".to_string(),
            Type::Float32 => "f32".to_string(),
            Type::Float64 => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "&str".to_string(),
            Type::Ptr(inner) | Type::Ref(inner) => {
                format!("&{}", self.generate_type(inner))
            },
            Type::MutRef(inner) => {
                format!("&mut {}", self.generate_type(inner))
            },
            Type::Array(inner, size) => {
                format!("[{}; {}]", self.generate_type(inner), size)
            },
            Type::Struct(name) => name.clone(),
        }
    }

    fn generate_function(&self, func: &Function) -> String {
        let mut code = String::new();
        
        let return_type = if matches!(func.return_type, Type::Void) {
            String::new()
        } else {
            format!(" -> {}", self.generate_type(&func.return_type))
        };
        
        let params = func.params
            .iter()
            .map(|(name, ty)| format!("{}: {}", name, self.generate_type(ty)))
            .collect::<Vec<_>>()
            .join(", ");
        
        code.push_str(&format!("fn {}({}){} {{\n", func.name, params, return_type));
        
        for inst in &func.body {
            code.push_str(&self.generate_instruction(inst));
        }
        
        code.push_str("}\n");
        code
    }

    fn generate_instruction(&self, inst: &Instruction) -> String {
        match inst {
            Instruction::Alloca { dest, ty } => {
                format!("    let mut {}: {};\n", dest, self.generate_type(ty))
            },
            Instruction::Store { dest, src } => {
                format!("    {} = {};\n", dest, src)
            },
            Instruction::Load { dest, src } => {
                format!("    let {} = {};\n", dest, src)
            },
            Instruction::Add { dest, left, right } => {
                format!("    let {} = {} + {};\n", dest, left, right)
            },
            Instruction::Sub { dest, left, right } => {
                format!("    let {} = {} - {};\n", dest, left, right)
            },
            Instruction::Mul { dest, left, right } => {
                format!("    let {} = {} * {};\n", dest, left, right)
            },
            Instruction::Div { dest, left, right } => {
                format!("    let {} = {} / {};\n", dest, left, right)
            },
            Instruction::Mod { dest, left, right } => {
                format!("    let {} = {} % {};\n", dest, left, right)
            },
            Instruction::Call { dest, func, args } => {
                if let Some(dest) = dest {
                    format!("    let {} = {}({});\n", dest, func, args.join(", "))
                } else {
                    format!("    {}({});\n", func, args.join(", "))
                }
            },
            Instruction::Return(value) => {
                if let Some(val) = value {
                    format!("    return {};\n", val)
                } else {
                    "    return;\n".to_string()
                }
            },
            Instruction::ReturnInPlace(value) => {
                format!("    {} // RVO\n", value)
            },
            _ => format!("    // {:?}\n", inst),
        }
    }
}

impl CodegenBackend for RustcBackend {
    fn name(&self) -> &str {
        "Rustc"
    }

    fn generate(&self, module: &Module) -> Result<String, Box<dyn Error>> {
        let mut code = String::new();
        
        code.push_str("// Generated by Chim Compiler - Rustc Backend\n");
        code.push_str("// Target: Rust Compiler\n");
        code.push_str("// Rust Edition: 2021\n\n");
        
        code.push_str("#![allow(non_snake_case)]\n");
        code.push_str("#![allow(unused_variables)]\n\n");
        
        for func in &module.functions {
            code.push_str(&self.generate_function(func));
            code.push_str("\n");
        }
        
        if module.functions.iter().any(|f| f.name == "main") {
            code.push_str("fn main() {\n");
            code.push_str("    main();\n");
            code.push_str("}\n");
        }
        
        Ok(code)
    }

    fn file_extension(&self) -> &str {
        "rs"
    }
}
