/* Generated by Chim Compiler - chibicc Backend */
/* Target: chibicc (Rui Ueyama's Small C Compiler) */
/* C11 Standard */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

int add(int a, int b);
int multiply(int x, int y);
void main(void);

int add(int a, int b) {
    int .tmp2 = b;
    int .tmp3 = .tmp2 + .tmp3;
    return .tmp3; /* RVO */
}

int multiply(int x, int y) {
    int .tmp5 = y;
    int .tmp6 = .tmp5 * .tmp6;
    return .tmp6; /* RVO */
}

void main(void) {
    int .tmp9 = add(.tmp7, .tmp8);
    int .tmp12 = multiply(.tmp10, .tmp11);
}

