// Generated by Chim Compiler - Clang C++ Backend
// Target: LLVM Clang with C++20
// Optimized for: Cache locality, SIMD, Branch prediction

#include <cstdint>
#include <cstdlib>
#include <array>
#include <memory>
#include <concepts>
#include <span>

// LLVM Optimization Attributes
#ifdef __clang__
#define CHIM_HOT __attribute__((hot))
#define CHIM_COLD __attribute__((cold))
#define CHIM_INLINE __attribute__((always_inline))
#define CHIM_PURE __attribute__((pure))
#else
#define CHIM_HOT
#define CHIM_COLD
#define CHIM_INLINE inline
#define CHIM_PURE
#endif

[[gnu::hot]] int32_t add(int32_t a, int32_t b) {
}

[[gnu::used]] [[gnu::hot]] void main() {
    auto .tmp4 = add(5, 10);
}

