/* Generated by Chim Compiler - 8cc Backend */
/* Target: 8cc (Rui Ueyama's Educational C Compiler) */
/* C89/C99 subset */

#include <stdio.h>
#include <stdlib.h>

int add(int a, int b) {
    int .tmp2 = b;
    int .tmp3 = .tmp2 + .tmp3;
    return .tmp3; /* RVO */
}

int multiply(int x, int y) {
    int .tmp5 = y;
    int .tmp6 = .tmp5 * .tmp6;
    return .tmp6; /* RVO */
}

void main(void) {
    int .tmp9 = add(.tmp7, .tmp8);
    int .tmp12 = multiply(.tmp10, .tmp11);
}

