// Generated by Chim Compiler - Java Backend
// Target: Java 11+
// Features: var syntax, type inference, modern APIs

public class ChimGenerated {

    public static int add(int a, int b) {
        var .tmp2 = b;
        var .tmp3 = .tmp2 + .tmp3;
        return .tmp3; // RVO
    }

    public static int multiply(int x, int y) {
        var .tmp5 = y;
        var .tmp6 = .tmp5 * .tmp6;
        return .tmp6; // RVO
    }

    public static void main() {
        var .tmp9 = add(.tmp7, .tmp8);
        var .tmp12 = multiply(.tmp10, .tmp11);
    }

    public static void main(String[] args) {
        main();
    }
}
