// Generated by Chim Compiler - Rustc Backend
// Target: Rust Compiler
// Rust Edition: 2021

#![allow(non_snake_case)]
#![allow(unused_variables)]

fn add(a: i32, b: i32) -> i32 {
    let .tmp1 = a + b;
    .tmp1 // RVO
}

fn subtract(a: i32, b: i32) -> i32 {
    let .tmp2 = a - b;
    .tmp2 // RVO
}

fn multiply(a: i32, b: i32) -> i32 {
    let .tmp3 = a * b;
    .tmp3 // RVO
}

fn divide(a: i32, b: i32) -> i32 {
    let .tmp4 = a / b;
    .tmp4 // RVO
}

fn modulo(a: i32, b: i32) -> i32 {
    let .tmp5 = a % b;
    .tmp5 // RVO
}

fn main() {
    let .tmp8 = add(10, 20);
    let .tmp11 = subtract(30, 15);
    let .tmp14 = multiply(5, 6);
    let .tmp17 = divide(100, 10);
    let .tmp20 = modulo(17, 5);
}

fn main() {
    main();
}
