# Generated by Chim Compiler - x86-64 Assembly Backend
# Target: x86_64-linux-gnu
# ABI: System V AMD64
# Syntax: AT&T
#

    .text
    .file   "chim_module.s"

    .globl add
    .type add, @function
add:
    pushq   %rbp
    movq    %rsp, %rbp
    movq    %rdi, -8(%rbp)  # param: a
    movq    %rsi, -16(%rbp)  # param: b

    movl    -8(%rbp), %eax  # load a
addl    -8(%rbp), %eax  # add b
movl    %eax, -8(%rbp)  # store .tmp1
    movl    -8(%rbp), %eax  # RVO return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size add, .-add

    .globl subtract
    .type subtract, @function
subtract:
    pushq   %rbp
    movq    %rsp, %rbp
    movq    %rdi, -8(%rbp)  # param: a
    movq    %rsi, -16(%rbp)  # param: b

    movl    -8(%rbp), %eax  # load a
subl    -8(%rbp), %eax  # sub b
movl    %eax, -8(%rbp)  # store .tmp2
    movl    -8(%rbp), %eax  # RVO return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size subtract, .-subtract

    .globl multiply
    .type multiply, @function
multiply:
    pushq   %rbp
    movq    %rsp, %rbp
    movq    %rdi, -8(%rbp)  # param: a
    movq    %rsi, -16(%rbp)  # param: b

    movl    -8(%rbp), %eax  # load a
imull   -8(%rbp), %eax  # mul b
movl    %eax, -8(%rbp)  # store .tmp3
    movl    -8(%rbp), %eax  # RVO return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size multiply, .-multiply

    .globl divide
    .type divide, @function
divide:
    pushq   %rbp
    movq    %rsp, %rbp
    movq    %rdi, -8(%rbp)  # param: a
    movq    %rsi, -16(%rbp)  # param: b

    movl    -8(%rbp), %eax  # load a
cltd                     # sign extend
idivl   -8(%rbp)         # div b
movl    %eax, -8(%rbp)  # store .tmp4
    movl    -8(%rbp), %eax  # RVO return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size divide, .-divide

    .globl modulo
    .type modulo, @function
modulo:
    pushq   %rbp
    movq    %rsp, %rbp
    movq    %rdi, -8(%rbp)  # param: a
    movq    %rsi, -16(%rbp)  # param: b

    # Mod { dest: ".tmp5", left: "a", right: "b" }
    movl    -8(%rbp), %eax  # RVO return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size modulo, .-modulo

    .globl main
    .type main, @function
main:
    pushq   %rbp
    movq    %rsp, %rbp

    movl    -8(%rbp), %di  # arg 0
    movl    -8(%rbp), %si  # arg 1
    call    add
    movl    %eax, -8(%rbp)  # save return
    movl    -8(%rbp), %di  # arg 0
    movl    -8(%rbp), %si  # arg 1
    call    subtract
    movl    %eax, -8(%rbp)  # save return
    movl    -8(%rbp), %di  # arg 0
    movl    -8(%rbp), %si  # arg 1
    call    multiply
    movl    %eax, -8(%rbp)  # save return
    movl    -8(%rbp), %di  # arg 0
    movl    -8(%rbp), %si  # arg 1
    call    divide
    movl    %eax, -8(%rbp)  # save return
    movl    -8(%rbp), %di  # arg 0
    movl    -8(%rbp), %si  # arg 1
    call    modulo
    movl    %eax, -8(%rbp)  # save return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size main, .-main


    .section .note.GNU-stack,"",@progbits
