// Generated by Chim Compiler - Rustc Backend
// Target: Rust Compiler
// Rust Edition: 2021

#![allow(non_snake_case)]
#![allow(unused_variables)]

fn add(a: i32, b: i32) -> i32 {
    let .tmp2 = b;
    let .tmp3 = .tmp2 + .tmp3;
    .tmp3 // RVO
}

fn multiply(x: i32, y: i32) -> i32 {
    let .tmp5 = y;
    let .tmp6 = .tmp5 * .tmp6;
    .tmp6 // RVO
}

fn main() {
    let .tmp9 = add(.tmp7, .tmp8);
    let .tmp12 = multiply(.tmp10, .tmp11);
}

fn main() {
    main();
}
