// Generated by Chim Compiler - Objective-C Backend
// Target: Objective-C 2.0+
// Features: ARC enabled, modern syntax, blocks

#import <Foundation/Foundation.h>
#if !__has_feature(objc_arc)
#error "ARC is required for this file"
#endif

int add(int a, int b);
int multiply(int x, int y);
void main(void);

int add(int a, int b) {
    id .tmp2 = b;
    id .tmp3 = .tmp2 + .tmp3;
    return .tmp3; // RVO
}

int multiply(int x, int y) {
    id .tmp5 = y;
    id .tmp6 = .tmp5 * .tmp6;
    return .tmp6; // RVO
}

void main(void) {
    id .tmp9 = add(.tmp7, .tmp8);
    id .tmp12 = multiply(.tmp10, .tmp11);
}

// Entry point
int main(int argc, const char * argv[]) {
    @autoreleasepool {
        main();
    }
    return 0;
}
