// Generated by Chim Compiler - C# Backend
// Target: C# 9.0+ (.NET 5.0+)
// Features: top-level statements, var, nullable references

using System;
using System.Collections.Generic;
#nullable enable

public class ChimGenerated
{
    static int Add(int a, int b)
    {
        var .tmp2 = b;
        var .tmp3 = .tmp2 + .tmp3;
        return .tmp3; // RVO
    }

    static int Multiply(int x, int y)
    {
        var .tmp5 = y;
        var .tmp6 = .tmp5 * .tmp6;
        return .tmp6; // RVO
    }

    static void Main()
    {
        var .tmp9 = Add(.tmp7, .tmp8);
        var .tmp12 = Multiply(.tmp10, .tmp11);
    }

    static void Main(string[] args)
    {
        Main();
    }
}
