# Generated by Chim Compiler - Nim Backend
# Target: Nim Language
# Features: metaprogramming, compiles to C/C++, high performance

import std/[os, strutils]

proc add(a: int32; b: int32): int32 =
  var .tmp2 = b
  var .tmp3 = .tmp2 + .tmp3
  result = .tmp3 # RVO

proc multiply(x: int32; y: int32): int32 =
  var .tmp5 = y
  var .tmp6 = .tmp5 * .tmp6
  result = .tmp6 # RVO

proc main() =
  var .tmp9 = add(.tmp7, .tmp8)
  var .tmp12 = multiply(.tmp10, .tmp11)

# Main entry point
when isMainModule:
  discard main()
