// Generated by Chim Compiler - Kotlin Backend
// Target: Kotlin 1.8+
// Features: data classes, coroutines, null-safety

package chim.generated

fun add(a: Int, b: Int): Int {
    val .tmp2 = b
    val .tmp3 = .tmp2 + .tmp3
    return .tmp3 // RVO
}

fun multiply(x: Int, y: Int): Int {
    val .tmp5 = y
    val .tmp6 = .tmp5 * .tmp6
    return .tmp6 // RVO
}

fun main() {
    val .tmp9 = add(.tmp7, .tmp8)
    val .tmp12 = multiply(.tmp10, .tmp11)
}

// Entry point
fun main(args: Array<String>) {
    main()
}
