// Generated by Chim Compiler - Kotlin Backend
// Target: Kotlin 1.8+
// Features: data classes, coroutines, null-safety

package chim.generated

fun add(a: Int, b: Int): Int {
    val .tmp1 = a + b
    return .tmp1 // RVO
}

fun subtract(a: Int, b: Int): Int {
    val .tmp2 = a - b
    return .tmp2 // RVO
}

fun multiply(a: Int, b: Int): Int {
    val .tmp3 = a * b
    return .tmp3 // RVO
}

fun divide(a: Int, b: Int): Int {
    val .tmp4 = a / b
    return .tmp4 // RVO
}

fun modulo(a: Int, b: Int): Int {
    val .tmp5 = a % b
    return .tmp5 // RVO
}

fun main() {
    val .tmp8 = add(10, 20)
    val .tmp11 = subtract(30, 15)
    val .tmp14 = multiply(5, 6)
    val .tmp17 = divide(100, 10)
    val .tmp20 = modulo(17, 5)
}

// Entry point
fun main(args: Array<String>) {
    main()
}
