// Generated by Chim Compiler - V Backend
// Target: V Language
// Features: autofree, compile-time safety, zero dependencies

module main

fn add(a int, b int) int {
	.tmp2 := b
	.tmp3 := .tmp2 + .tmp3
	return .tmp3 // RVO
}

fn multiply(x int, y int) int {
	.tmp5 := y
	.tmp6 := .tmp5 * .tmp6
	return .tmp6 // RVO
}

fn main() {
	.tmp9 := add(.tmp7, .tmp8)
	.tmp12 := multiply(.tmp10, .tmp11)
}

