// Generated by Chim Compiler - Swift Backend
// Target: Swift 5.0+
// Features: strong types, optionals, value semantics

import Foundation

func add(a: Int32, b: Int32) -> Int32 {
    let .tmp2 = b
    let .tmp3 = .tmp2 + .tmp3
    return .tmp3 // RVO
}

func multiply(x: Int32, y: Int32) -> Int32 {
    let .tmp5 = y
    let .tmp6 = .tmp5 * .tmp6
    return .tmp6 // RVO
}

func main() {
    let .tmp9 = add(.tmp7, .tmp8)
    let .tmp12 = multiply(.tmp10, .tmp11)
}

// Entry point
main()
