// Generated by Chim Compiler - JavaScript Backend
// Target: ES6+ (ECMAScript 2015+)
// Features: const/let, arrow functions, modules

'use strict';

function add(a, b) {
  const .tmp1 = a + b;
  return .tmp1; // RVO
}

function subtract(a, b) {
  const .tmp2 = a - b;
  return .tmp2; // RVO
}

function multiply(a, b) {
  const .tmp3 = a * b;
  return .tmp3; // RVO
}

function divide(a, b) {
  const .tmp4 = a / b;
  return .tmp4; // RVO
}

function modulo(a, b) {
  const .tmp5 = a % b;
  return .tmp5; // RVO
}

function main() {
}

// Export functions
module.exports = {
  add,
  subtract,
  multiply,
  divide,
  modulo,
  main
};
