// Generated by Chim Compiler - JavaScript Backend
// Target: ES6+ (ECMAScript 2015+)
// Features: const/let, arrow functions, modules

'use strict';

function add(a, b) {
  const .tmp2 = b;
  const .tmp3 = .tmp2 + .tmp3;
  return .tmp3; // RVO
}

function multiply(x, y) {
  const .tmp5 = y;
  const .tmp6 = .tmp5 * .tmp6;
  return .tmp6; // RVO
}

function main() {
  const .tmp9 = add(.tmp7, .tmp8);
  const .tmp12 = multiply(.tmp10, .tmp11);
}

// Export functions
module.exports = {
  add,
  multiply,
  main
};
