// Generated by Chim Compiler - Java Backend
// Target: Java 11+
// Features: var syntax, type inference, modern APIs

public class ChimGenerated {

    public static int add(int a, int b) {
        var .tmp1 = a + b;
        return .tmp1; // RVO
    }

    public static int subtract(int a, int b) {
        var .tmp2 = a - b;
        return .tmp2; // RVO
    }

    public static int multiply(int a, int b) {
        var .tmp3 = a * b;
        return .tmp3; // RVO
    }

    public static int divide(int a, int b) {
        var .tmp4 = a / b;
        return .tmp4; // RVO
    }

    public static int modulo(int a, int b) {
        var .tmp5 = a % b;
        return .tmp5; // RVO
    }

    public static void main() {
    }

    public static void main(String[] args) {
        main();
    }
}
