// Generated by Chim Compiler - Swift Backend
// Target: Swift 5.0+
// Features: strong types, optionals, value semantics

import Foundation

func add(a: Int32, b: Int32) -> Int32 {
    let .tmp1 = a + b
    return .tmp1 // RVO
}

func subtract(a: Int32, b: Int32) -> Int32 {
    let .tmp2 = a - b
    return .tmp2 // RVO
}

func multiply(a: Int32, b: Int32) -> Int32 {
    let .tmp3 = a * b
    return .tmp3 // RVO
}

func divide(a: Int32, b: Int32) -> Int32 {
    let .tmp4 = a / b
    return .tmp4 // RVO
}

func modulo(a: Int32, b: Int32) -> Int32 {
    let .tmp5 = a % b
    return .tmp5 // RVO
}

func main() {
    let .tmp8 = add(10, 20)
    let .tmp11 = subtract(30, 15)
    let .tmp14 = multiply(5, 6)
    let .tmp17 = divide(100, 10)
    let .tmp20 = modulo(17, 5)
}

// Entry point
main()
