/* Generated by Chim Compiler - GCC Backend */
/* Target: GNU Compiler Collection */
/* GNU C Extensions enabled */

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

__attribute__((hot))
int32_t add(int32_t a, int32_t b) {
    __auto_type .tmp2 = b;
    __auto_type .tmp3 = .tmp2 + .tmp3;
    return .tmp3; /* RVO */
}

__attribute__((hot))
int32_t multiply(int32_t x, int32_t y) {
    __auto_type .tmp5 = y;
    __auto_type .tmp6 = .tmp5 * .tmp6;
    return .tmp6; /* RVO */
}

__attribute__((hot))
void main() {
    __auto_type .tmp9 = add(.tmp7, .tmp8);
    __auto_type .tmp12 = multiply(.tmp10, .tmp11);
}

