// Generated by Chim Compiler - TypeScript Backend
// Target: TypeScript 4.0+
// Features: strict types, interfaces, modern ES

/* eslint-disable */
// @ts-check

function add(a: number, b: number): number {
  const .tmp2 = b;
  const .tmp3: number = .tmp2 + .tmp3;
  return .tmp3; // RVO
}

function multiply(x: number, y: number): number {
  const .tmp5 = y;
  const .tmp6: number = .tmp5 * .tmp6;
  return .tmp6; // RVO
}

function main(): void {
  const .tmp9 = add(.tmp7, .tmp8);
  const .tmp12 = multiply(.tmp10, .tmp11);
}

// Export functions
export {
  add,
  multiply,
  main
};
