# Generated by Chim Compiler
# 启语(Chim)语言

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'runtime_py'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'compiler'))
from chim_runtime import 输出, 范围, send, recv

def test_basic():
    # 组: data (批量释放)
    try:
        x = 42
        输出('组内值:', x)
    finally:
        pass  # 组 'data' 结束，自动释放资源
    输出('组外完成')

def 主():
    test_basic()

if __name__ == '__main__':
    主()