# Generated by Chim Compiler
# 启语(Chim)语言

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'runtime_py'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'compiler'))
from chim_runtime import 输出, 范围, send, recv

def test():
    # 组: 临时 (批量释放)
    try:
        x = 100
        s = list(x) if isinstance(x, list) else x  # 快照
        输出(s)
    finally:
        pass  # 组 '临时' 结束，自动释放资源
    输出('done')

def 主():
    test()

if __name__ == '__main__':
    主()