// Generated by Chim Compiler
// Zig Backend

const std = @import("std");

fn add(a: i64, b: i64) i64 {
    return (a + b);
}

pub fn main() void {
    const x = 10;
    const y = 20;
    const result = add(x, y);
    std.debug.print("结果:" ++ " ", .{}); std.debug.print("{} ", .{result}); std.debug.print("\n", .{});
}
