// Generated by Chim Compiler
// Zig Backend

const std = @import("std");

fn test_group() void {
    // 组: 临时数据
    {
        const x = 100;
        const y = 200;
        std.debug.print("组内:" ++ " ", .{}); std.debug.print("{} ", .{x}); std.debug.print("{} ", .{y}); std.debug.print("\n", .{});
        // defer: 组 '临时数据' 结束
    }
    std.debug.print("组外完成" ++ "\n", .{});
}

pub fn main() void {
    test_group();
}
