# Generated by Chim Compiler
# 启语(Chim)语言

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'runtime_py'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'compiler'))
from chim_runtime import 输出, 范围, send, recv

def test_snapshot():
    # 返回类型: 整数
    # 组: temp (批量释放)
    try:
        nums = [10, 20, 30]
        snap = list(nums) if isinstance(nums, list) else nums  # 快照
        输出('快照:', snap)
    finally:
        pass  # 组 'temp' 结束，自动释放资源
    return 100

def 主():
    result = test_snapshot()
    输出('结果:', result)

if __name__ == '__main__':
    主()