// Generated by Chim Compiler
// Zig Backend

const std = @import("std");

fn add(a: i64, b: i64) i64 {
    return (a + b);
}

pub fn main() void {
    std.debug.print("计算结果:" ++ "\n", .{});
    const x = 10;
    const y = 20;
    const result = add(x, y);
    std.debug.print("x =" ++ " ", .{}); std.debug.print("{} ", .{x}); std.debug.print("\n", .{});
    std.debug.print("y =" ++ " ", .{}); std.debug.print("{} ", .{y}); std.debug.print("\n", .{});
    std.debug.print("x + y =" ++ " ", .{}); std.debug.print("{} ", .{result}); std.debug.print("\n", .{});
}
