// Generated by Chim Compiler - V Backend
// Target: V Language
// Features: autofree, compile-time safety, zero dependencies

module main

fn test_struct_layout() {
	.tmp1 := const.string."BadLayout created"
	println(.tmp1)
}

fn create_point() int {
	return .tmp1 // RVO
}

fn test_stack_allocation() {
	.tmp3 := const.string."Points created on stack"
	println(.tmp3)
}

fn main() {
	.tmp1 := println(.tmp1)
	.tmp4 := println(.tmp3)
	.tmp6 := const.string."All tests passed!"
	println(.tmp6)
}

