// Generated by Chim Compiler - JavaScript Backend
// Target: ES6+ (ECMAScript 2015+)
// Features: const/let, arrow functions, modules

'use strict';

function test_struct_layout() {
  const .tmp1 = const.string."BadLayout created";
  println(.tmp1);
}

function create_point() {
  return .tmp1; // RVO
}

function test_stack_allocation() {
  const .tmp3 = const.string."Points created on stack";
  println(.tmp3);
}

function main() {
  const .tmp1 = println(.tmp1);
  const .tmp4 = println(.tmp3);
  const .tmp6 = const.string."All tests passed!";
  println(.tmp6);
}

// Export functions
module.exports = {
  test_struct_layout,
  create_point,
  test_stack_allocation,
  main
};
