# Generated by Chim Compiler - Nim Backend
# Target: Nim Language
# Features: metaprogramming, compiles to C/C++, high performance

import std/[os, strutils]

proc test_struct_layout() =
  var .tmp1 = const.string."BadLayout created"
  println(.tmp1)

proc create_point(): int32 =
  result = .tmp1 # RVO

proc test_stack_allocation() =
  var .tmp3 = const.string."Points created on stack"
  println(.tmp3)

proc main() =
  var .tmp1 = println(.tmp1)
  var .tmp4 = println(.tmp3)
  var .tmp6 = const.string."All tests passed!"
  println(.tmp6)

# Main entry point
when isMainModule:
  discard main()
