! Generated by Chim Compiler - LLVM Flang Backend
! Target: LLVM Flang with Fortran 2023
! Optimized for: Scientific computing, Array operations, Parallelism

MODULE chim_module
    IMPLICIT NONE
    ! LLVM Flang optimization hints
    !DIR$ OPTIMIZE:3
    !DIR$ VECTOR ALWAYS

CONTAINS

SUBROUTINE test_struct_layout()
    IMPLICIT NONE

    ! Local variables

    ! Function body
    .tmp1 = const.string."BadLayout created"
    CALL println(.tmp1)
END SUBROUTINE test_struct_layout

FUNCTION create_point() RESULT(result_var)
    IMPLICIT NONE
    INTEGER(KIND=4) :: result_var

    ! Local variables

    ! Function body
    result_var = .tmp1 ! RVO
    RETURN
END FUNCTION create_point

SUBROUTINE test_stack_allocation()
    IMPLICIT NONE

    ! Local variables

    ! Function body
    .tmp3 = const.string."Points created on stack"
    CALL println(.tmp3)
END SUBROUTINE test_stack_allocation

SUBROUTINE main()
    IMPLICIT NONE

    ! Local variables

    ! Function body
    .tmp1 = println(.tmp1)
    .tmp4 = println(.tmp3)
    .tmp6 = const.string."All tests passed!"
    CALL println(.tmp6)
END SUBROUTINE main

END MODULE chim_module

PROGRAM chim_main
    USE chim_module
    IMPLICIT NONE
    INTEGER(KIND=4) :: exit_code

    exit_code = main()
    STOP exit_code
END PROGRAM chim_main
