// Generated by Chim Compiler - C# Backend
// Target: C# 9.0+ (.NET 5.0+)
// Features: top-level statements, var, nullable references

using System;
using System.Collections.Generic;
#nullable enable

public class ChimGenerated
{
    static void TestStructLayout()
    {
        var .tmp1 = const.string."BadLayout created";
        Println(.tmp1);
    }

    static int CreatePoint()
    {
        return .tmp1; // RVO
    }

    static void TestStackAllocation()
    {
        var .tmp3 = const.string."Points created on stack";
        Println(.tmp3);
    }

    static void Main()
    {
        var .tmp1 = Println(.tmp1);
        var .tmp4 = Println(.tmp3);
        var .tmp6 = const.string."All tests passed!";
        Println(.tmp6);
    }

    static void Main(string[] args)
    {
        Main();
    }
}
