// Generated by Chim Compiler - TypeScript Backend
// Target: TypeScript 4.0+
// Features: strict types, interfaces, modern ES

/* eslint-disable */
// @ts-check

function test_struct_layout(): void {
  const .tmp1 = const.string."BadLayout created";
  println(.tmp1);
}

function create_point(): number {
  return .tmp1; // RVO
}

function test_stack_allocation(): void {
  const .tmp3 = const.string."Points created on stack";
  println(.tmp3);
}

function main(): void {
  const .tmp1 = println(.tmp1);
  const .tmp4 = println(.tmp3);
  const .tmp6 = const.string."All tests passed!";
  println(.tmp6);
}

// Export functions
export {
  test_struct_layout,
  create_point,
  test_stack_allocation,
  main
};
