// Generated by Chim Compiler - Clang C++ Backend
// Target: LLVM Clang with C++20
// Optimized for: Cache locality, SIMD, Branch prediction

#include <cstdint>
#include <cstdlib>
#include <array>
#include <memory>
#include <concepts>
#include <span>

// LLVM Optimization Attributes
#ifdef __clang__
#define CHIM_HOT __attribute__((hot))
#define CHIM_COLD __attribute__((cold))
#define CHIM_INLINE __attribute__((always_inline))
#define CHIM_PURE __attribute__((pure))
#else
#define CHIM_HOT
#define CHIM_COLD
#define CHIM_INLINE inline
#define CHIM_PURE
#endif

[[gnu::hot]] void test_struct_layout() {
    auto .tmp1 = const.string."BadLayout created";
    println(.tmp1);
}

[[gnu::hot]] int32_t create_point() {
    return .tmp1; // RVO
}

[[gnu::hot]] void test_stack_allocation() {
    auto .tmp3 = const.string."Points created on stack";
    println(.tmp3);
}

[[gnu::used]] [[gnu::hot]] void main() {
    auto .tmp1 = println(.tmp1);
    auto .tmp4 = println(.tmp3);
    auto .tmp6 = const.string."All tests passed!";
    println(.tmp6);
}

