# Generated by Chim Compiler - x86-64 Assembly Backend
# Target: x86_64-linux-gnu
# ABI: System V AMD64
# Syntax: AT&T
#

    .text
    .file   "chim_module.s"

    .globl test_struct_layout
    .type test_struct_layout, @function
test_struct_layout:
    pushq   %rbp
    movq    %rsp, %rbp

    movl    -8(%rbp), %eax  # load .tmp0
movl    %eax, -8(%rbp)  # store to obj
    movl    -8(%rbp), %eax  # load from const.string."BadLayout created"
movl    %eax, -8(%rbp)  # store to .tmp1
    movl    -8(%rbp), %di  # arg 0
    call    println
    movq    %rbp, %rsp
popq    %rbp
ret
    .size test_struct_layout, .-test_struct_layout

    .globl create_point
    .type create_point, @function
create_point:
    pushq   %rbp
    movq    %rsp, %rbp

    movl    -8(%rbp), %eax  # RVO return
    movq    %rbp, %rsp
popq    %rbp
ret
    .size create_point, .-create_point

    .globl test_stack_allocation
    .type test_stack_allocation, @function
test_stack_allocation:
    pushq   %rbp
    movq    %rsp, %rbp

    movl    -8(%rbp), %eax  # load .tmp1
movl    %eax, -8(%rbp)  # store to p1
    call    create_point
    movl    %eax, -8(%rbp)  # save return
    movl    -8(%rbp), %eax  # load .tmp2
movl    %eax, -8(%rbp)  # store to p2
    movl    -8(%rbp), %eax  # load from const.string."Points created on stack"
movl    %eax, -8(%rbp)  # store to .tmp3
    movl    -8(%rbp), %di  # arg 0
    call    println
    movq    %rbp, %rsp
popq    %rbp
ret
    .size test_stack_allocation, .-test_stack_allocation

    .globl main
    .type main, @function
main:
    pushq   %rbp
    movq    %rsp, %rbp

    call    test_struct_layout
    movl    %eax, -8(%rbp)  # save return
    call    test_stack_allocation
    movl    %eax, -8(%rbp)  # save return
    movl    -8(%rbp), %eax  # load from const.string."All tests passed!"
movl    %eax, -8(%rbp)  # store to .tmp6
    movl    -8(%rbp), %di  # arg 0
    call    println
    movq    %rbp, %rsp
popq    %rbp
ret
    .size main, .-main


    .section .note.GNU-stack,"",@progbits
