// Generated by Chim Compiler - Java Backend
// Target: Java 11+
// Features: var syntax, type inference, modern APIs

public class ChimGenerated {

    public static void test_struct_layout() {
        var .tmp1 = const.string."BadLayout created";
        println(.tmp1);
    }

    public static int create_point() {
        return .tmp1; // RVO
    }

    public static void test_stack_allocation() {
        var .tmp3 = const.string."Points created on stack";
        println(.tmp3);
    }

    public static void main() {
        var .tmp1 = println(.tmp1);
        var .tmp4 = println(.tmp3);
        var .tmp6 = const.string."All tests passed!";
        println(.tmp6);
    }

    public static void main(String[] args) {
        main();
    }
}
