# Generated by Chim Compiler
# 启语(Chim)语言

import arch.x86_64 as x86
import 调度.调度器 as sched
import 用户.init as usr
import io.serial as io

def 主():
    io.输出(chym)
    x86.引导()
    usr.初始化()
    sched.运行()
